### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by axsddlr** [PaoloRotolo/GittyReporter#3]
some issue

Debug-infos:
 OS Version: 3.4.0-g69cae49(1227fed3bc)
 OS API Level: 22
 Device: m8
 Model (and Product): One M8 (m8)
 RELEASE: 5.1.1
 BRAND: htc
 DISPLAY: LYZ28E test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 Build ID: LYZ28E
 MANUFACTURER: htc
 SERIAL: FA447WM00930
 USER: aospal
 HOST: buildbox-01.hostingsharedbox.com

Extra Info: Nothing to show.

**Comment by paolorotolo** [comment]
Yes, it works :D
