### ISSUE TITLE
Test title

### ISSUE THREAD

**Issue by janheinrichmerker** [PaoloRotolo/GittyReporter#8]
Something doesn't work

Debug info:
 OS Version: 3.4.0-gbebb36b(1863243)
 OS API Level: 22
 Device: hammerhead
 Model (and Product): Nexus 5 (hammerhead)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY48B
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: hammerhead
 Build ID: LMY48B
 MANUFACTURER: LGE
 SERIAL: 04aa1964438381e8
 USER: android-build
 HOST: wpiu6.hot.corp.google.com

Extra Info: Nothing to show.

**Comment by paolorotolo** [comment]
Yes, it works. :D
